version: "3.3"
services:
  transmission:
    image: amitie10g/docker-transmission:gdrive-ocamlfuse
    container_name: transmission
    environment:
      - PUID=
      - PGID=
      - LOCAL_HOME=
      - MOUNT_OPTS=
      - CLIENT_ID=
      - CLIENT_SECRET=
      - TZ=UTC
      - TRANSMISSION_WEB_HOME=/combustion-release/
    volumes:
      - <path to data>:/config
      - <path to watch folder>:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
