#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
  /downloads/complete \
  /donwloads/incomplete \
  /config \
  /watch

# copy config
[[ ! -f /config/settings.json ]] && cp \
  /defaults/settings.json /config/settings.json

# copy blocklist-update script
[[ ! -f /config/blocklist-update.sh ]] && cp \
  /defaults/blocklist-update.sh /config/blocklist-update.sh

# permissions
chown abc:abc \
  /config/settings.json \
  /config/blocklist-update.sh \
  /downloads \
  /watch

chmod 755 /config/blocklist-update.sh

# mount /download/complete to GCS bucket, if key files exists
if [ -f "/config/gcs-key.json" ]; then

  # permissions
  chown abc:abc \
    /config/gcs-key.json
  
  # run gcsfuse
  echo "$BUCKET /downloads/complete gcsfuse rw,user,noauto,key_file=/config/gcs-key.json" >> /etc/fstab
  s6-setuidgid abc mount.gcsfuse $BUCKET /downloads/complete
fi
