#!/bin/bash

DRIVE_PATH=/downloads/complete

# Functions
setup(){
  echo "Initialising google-drive-ocamlfuse..."
  echo "$VERIFICATION_CODE"
  env HOME=/config s6-setuidgid abc google-drive-ocamlfuse \
    -label "$LABEL" \
    -f \
    -cc \
    -skiptrash \
    -headless \
    -id "$CLIENT_ID.apps.googleusercontent.com" \
    -secret "$CLIENT_SECRET"
  mount
}

mount() {
  echo "Mounting at $DRIVE_PATH..."
  env HOME=/config s6-setuidgid abc google-drive-ocamlfuse $DRIVE_PATH \
    -o "noatime,uid=$PUID,gid=$PGID" \
    -label "$LABEL" \
    -f \
    -cc \
    -skiptrash \
    -headless

}

# begin gdrive-ocamlfuse startup
if [ -e "/config/.gdfuse/$LABEL/config" ]; then
  echo "Notice: No Google Drive configuration found."
else
  if [ -z "$CLIENT_ID" ]; then
    echo "Fatal: no CLIENT_ID found -> EXIT"
    exit 1
  elif [ -z "$CLIENT_SECRET" ]; then
    echo "Fatal: no CLIENT_SECRET found -> EXIT"
    exit 1
  elif [ -z "$VERIFICATION_CODE" ]; then
    echo "Warning: no VERIFICATION_CODE found"
    [[ $- == *i* ]] && setup || timeout 30 setup
  else
    setup
  fi
fi
